[package]
name = "biblapp"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arboard = "3.4"
directories = "5.0"

# Original language support
csv = "1.3"
unicode-normalization = "0.1"
bincode = "1.3"

[package.metadata.bundle]
name = "Bible App"
identifier = "com.github.Divhanthelion/Bible-App"
icon = ["icon.png"]
resources = ["new_testament", "old_testament", "icon.png"]
short_description = "Project Gutenberg KJV"
long_description = """
Displays each the bible one chapter at a time. 
Featuring a blazing fast search feature which doubles as a word count.
"""
