//! Verse alignment tables: `data/library/alignment/<id>.tsv`.
//!
//! For each translation, the verses whose KJV counterpart is not simply the KJV
//! verse with the same book, chapter, and number, found by content
//! (kjv_library::align). Every verse not listed corresponds to its same-numbered
//! KJV verse. The tables are reviewable: each row says how it was matched and how
//! similar the texts are.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;

use kjv_library::align::{self, How, Verse};
use kjv_library::usfm::{self, Options};

use crate::bibles::{Mode, catalogue};
use crate::library;

fn how_name(h: How) -> &'static str {
    match h {
        How::Content => "content",
        How::Framed => "framed",
        How::Moved => "moved",
        How::Number => "number",
        How::Unmatched => "unmatched",
    }
}

/// Every verse of translation `id`'s book `code`, from data/library/bibles.
fn verses(id: &str, code: &str, markers: &[String]) -> Option<Vec<Verse>> {
    let src = fs::read_to_string(library().join("bibles").join(id).join(format!("{}.usfm", code))).ok()?;
    let book = usfm::parse(&src.replace("\r\n", "\n"), &Options { heading_markers: markers.to_vec() }).ok()?;
    Some(usfm::verses(&book).into_iter().map(|v| Verse { chapter: v.chapter, number: v.number, title: v.title, text: v.text }).collect())
}

fn reference(chapter: u32, number: &str) -> String {
    format!("{}:{}", chapter, number)
}

/// The table for translation `id`.
fn table(id: &str, markers: &[String], kjv_markers: &[String]) -> Result<String, String> {
    let mut rows = String::new();
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    let mut total = 0usize;
    let kjv = |code: &str| verses("kjv", code, kjv_markers);
    for b in kjv_library::books::BOOKS {
        let Some(native) = verses(id, b.code, markers) else { continue };
        total += native.len();
        for row in align::align_book(b.code, &native, &kjv) {
            if row.native.is_empty() || row.is_same_number() {
                continue;
            }
            *counts.entry(how_name(row.how)).or_default() += row.native.len();
            let here: Vec<String> = row.native.iter().map(|(c, n)| reference(*c, n)).collect();
            let there: Vec<String> = row.kjv.iter().map(|(k, c, n)| format!("{} {}", k, reference(*c, n))).collect();
            writeln!(
                rows,
                "{}\t{}\t{}\t{}\t{:.2}",
                row.book,
                here.join("+"),
                if there.is_empty() { "-".to_string() } else { there.join("+") },
                how_name(row.how),
                row.score
            )
            .unwrap();
        }
    }
    let listed: usize = counts.values().sum();
    let mut out = String::new();
    writeln!(out, "# Generated by kjv-import from data/library/bibles/{} and the KJV. Do not edit.", id).unwrap();
    writeln!(out, "# The verses of this translation whose KJV counterpart is not the KJV verse with the same").unwrap();
    writeln!(out, "# book, chapter, and number, found by comparing the texts (crates/library/src/align.rs).").unwrap();
    writeln!(out, "# Every verse not listed corresponds to its same-numbered KJV verse, where the KJV has one.").unwrap();
    writeln!(out, "# Columns: book, verses here, KJV verses (\"-\": none), how matched, similarity (0-1).").unwrap();
    writeln!(
        out,
        "# {} verses, {} listed: {}",
        total,
        listed,
        counts.iter().map(|(k, v)| format!("{} {}", k, v)).collect::<Vec<_>>().join(", ")
    )
    .unwrap();
    Ok(out + &rows)
}

pub fn build(ids: &[String], mode: Mode) -> Result<(), String> {
    let all = catalogue()?;
    let kjv_markers = all.iter().find(|b| b.id == "kjv").map(|b| b.heading_markers.clone()).unwrap_or_default();
    let dir = library().join("alignment");
    let mut problems = Vec::new();
    for b in all.iter().filter(|b| b.id != "kjv" && (ids.is_empty() || ids.contains(&b.id))) {
        let text = table(&b.id, &b.heading_markers, &kjv_markers)?;
        let path = dir.join(format!("{}.tsv", b.id));
        match mode {
            Mode::Write => {
                fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
                fs::write(&path, &text).map_err(|e| e.to_string())?;
                println!("{:<11} {}", b.id, text.lines().nth(5).unwrap_or("").trim_start_matches("# "));
            }
            Mode::Check => match fs::read_to_string(&path) {
                Ok(disk) if disk.replace("\r\n", "\n") == text => {}
                Ok(_) => problems.push(format!("alignment/{}.tsv differs from what the texts produce", b.id)),
                Err(_) => problems.push(format!("alignment/{}.tsv is missing", b.id)),
            },
        }
    }
    if problems.is_empty() { Ok(()) } else { Err(problems.join("\n")) }
}
